name = "CSJLab"
uuid = "20247e0c-133c-11ea-2166-8b5f0e6be241"
authors = ["jfjhh <alex.striff1@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
